application: daniudacitycs253
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /styles
  static_dir: styles

- url: /.*
  script: helloudacity.app

libraries:
- name: jinja2
  version: latest